default: &default
  adapter: mysql2
  host: localhost
  username: root
  password: 123456
  pool: 5
  timeout: 5000

default: &dev
  adapter: mysql2
  host: localhost 
  username: root
  password: 123456 
  pool: 5
  timeout: 5000

development:
  <<: *dev
  database: imagemanager

test:
  <<: *dev
  database: imagemanagerteste

production:
  <<: *default
  database: imagemanager